### ISSUE TITLE
Update SHEDS Theme and Splash Page

### ISSUE THREAD

**Issue by walkerjeffd** [Conte-Ecology/home#7]
Jeff/Chris

Select a new Bootstrap theme:
- http://bootswatch.com/
- http://bootstrapzero.com/
- http://startbootstrap.com/

Create better splash page
- Shows 3-4 maps of HUC-averaged metrics for stream temperature, fish
- Maps link to pre-configured data explorer

**Comment by djhocking** [comment]
HAving not worked with bootstrap it's a bit hard for me to imagine what you'd do with some of the themes (flexibility for design we want) but personally I like the bootswatch journal template: http://bootswatch.com/journal/

just my 2 cents at a glance

**Comment by djhocking** [comment]
http://bootstraptaste.com/theme/squadfree/ also looks nice but the example is just 1 page and I'm not sure how easy it would be to adjust for our purposes.

**Comment by walkerjeffd** [comment]
maybe we could set up some examples and everyone could vote. i personally
like http://bootswatch.com/flatly/

journal is nice, but the warning buttons/alerts (yellow) are unreadable

On Tue, Feb 17, 2015 at 11:44 AM, Daniel J. Hocking <
notifications@github.com> wrote:

> http://bootstraptaste.com/theme/squadfree/ also looks nice but the
> example is just 1 page and I'm not sure how easy it would be to adjust for
> our purposes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Conte-Ecology/home/issues/7#issuecomment-74700925>.
>



-- 
Jeffrey D. Walker, PhD
http://walkerjeff.com

**Comment by bletcher** [comment]
It's hard to think about what these will look like on our site without an
example. How easy is it to change the theme? I like the vote idea.

On Tue, Feb 17, 2015 at 12:24 PM, Jeff Walker <notifications@github.com>
wrote:

> maybe we could set up some examples and everyone could vote. i personally
> like http://bootswatch.com/flatly/
>
> journal is nice, but the warning buttons/alerts (yellow) are unreadable
>
>
> On Tue, Feb 17, 2015 at 11:44 AM, Daniel J. Hocking <
> notifications@github.com> wrote:
>
> > http://bootstraptaste.com/theme/squadfree/ also looks nice but the
> > example is just 1 page and I'm not sure how easy it would be to adjust
> for
> > our purposes.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Conte-Ecology/home/issues/7#issuecomment-74700925>.
> >
>
>
>
> --
> Jeffrey D. Walker, PhD
> http://walkerjeff.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Conte-Ecology/home/issues/7#issuecomment-74709880>.
>



-- 

 Silvio O. Conte Anadromous Fish Research Center, U.S. Geological Survey
 P.O. Box 796 -- One Migratory Way
 Turners Falls, MA 01376
 (413) 863-3803
 Cell: (413) 522-9417
 FAX (413) 863-9810

ben_letcher@usgs.gov
bletcher@eco.umass.edu
http://www.lsc.usgs.gov/?q=cafb-research

**Comment by walkerjeffd** [comment]
the bootswatch themes are very easy to switch (just change a single CSS file). the others would be more difficult requiring rewriting the html. but i think the others have some more impressive designs.

**Comment by jcoombs20** [comment]
I like http://bootswatch.com/cyborg/ for dark, and http://bootswatch.com/sandstone/ for light
